include classpath("application.conf")

node-address {
    protocol = http
    host = elasticmq
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = strict
}

rest-stats {
    enabled = true
    bind-port = 9325
    bind-hostname = "0.0.0.0"
}

generate-node-address = false
queues-storage {
    enabled = false
}

queues {
    fmlocal-events {
        defaultVisibilityTimeout = 10 seconds
        delay = 0 seconds
        receiveMessageWait = 0 seconds
        fifo = false
        contentBasedDeduplication = false
    }
}

aws {
    region = us-east-1
    accountId = "000000000000"
}
